# Generated by Django 5.1.4 on 2025-04-07 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_description_remove_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
